version = "3.7.15"
runner.dialect = scala213

maxColumn = 120
align.preset = more
align.openParenCallSite = false
align.openParenDefnSite = false
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings.style = Asterisk
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true
spaces {
  inImportCurlyBraces = true
}
optIn.annotationNewlines = true
newlines {
  alwaysBeforeMultilineDef = false
  sometimesBeforeColonInMethodReturnType = true
}
rewrite {
  rules = [
    SortImports,
    PreferCurlyFors,
    RedundantParens,
    SortModifiers
  ]
  redundantBraces.maxLines = 1
}
project.excludeFilters = [
  ".*\\.sbt$"
  ".*\\.sc$"
]